<?php
defined('APP_PATH') or exit('No direct script access allowed');
require_once('AppPath.php');
/* Do Not Edit This File. This File Created For System Functionality. */
class Base_Model
{
    protected $base_path; //Base Directory Path

    public function __construct()
    {
        $this->base_path = path();
    }

    function __call($method, $file_name)
    {

        //Load Helper
        if ($method == 'helper') {
            $file = "Helper ";
            $require = array();
            for ($i = 0; $i < count($file_name); $i++) {
                if (file_exists($this->base_path . 'helpers/' . $file_name[$i] . '.php')) {
                    $require[] = $this->base_path . 'helpers/' . $file_name[$i] . '.php';
                } else {
                    $file .= $file_name[$i] . ' ';
                }
            }

            if (count($file_name) == sizeof($require)) {
                foreach ($require as $key) {
                    require_once($key);
                }
            } else {
                return require_once($this->base_path . 'views/error/error.php');
                exit();
            }
        }

        //Load Library
        if ($method == 'library') {
            $file = "Library ";
            $require = array();
            for ($i = 0; $i < count($file_name); $i++) {
                if (file_exists($this->base_path . 'libraries/' . $file_name[$i] . '.php')) {
                    $require[] = $this->base_path . 'libraries/' . $file_name[$i] . '.php';
                } else {
                    $file .= $file_name[$i] . ' ';
                }
            }
            $i = 0;
            if (count($file_name) == sizeof($require)) {
                foreach ($require as $key) {
                    require_once($key);
                    $this->{$file_name[$i]} = new $file_name[$i];
                    $i++;
                }
            } else {
                return require_once($this->base_path . 'views/error/error.php');
                exit();
            }
        }

        //Load Database
        if ($method == 'database') {
            require_once($this->base_path . 'system/Core/QueryBuilder.php');
            if (count($file_name) == 0) :
                $this->db = new QueryBuilder('');
            else :
                $this->{$file_name[0]} = new QueryBuilder($file_name[0]);
            endif;
        }
    }
}
