<?php
    defined('APP_PATH') OR exit('No direct script access allowed');
    /* Do Not Edit This File. This File Created For System Functionality. */
    class My_Controller {
        public $base_path; //Base Dir Path

        public function __construct() {
			$root = ['system'];
			$path = str_replace('\\', '/', __DIR__);
			$path = explode('/', $path);

			$path = array_values(array_filter(array_diff($path, $root)));

			foreach ($path as $key) {
				$this->base_path.= $key.'/';
            }
            
            if(APP_URL != "") {
                $this->base_path = "";
            }
        }

        function __call($method, $file_name) {
            //Load View
            if ($method == 'view') {
                $file = "View ";
                switch(count($file_name)) {
                    case 1 : 
                        if (file_exists($this->base_path.'views/'.$file_name[0].'.php')) {
                            require_once($this->base_path.'views/'.$file_name[0].'.php');
                        }else {
                            $file.= $file_name[0];
                            return require_once($this->base_path.'views/error/error.php');
                        }
                    case 2 :
                        if (isset($file_name[1]))
                            is_array($file_name[1]) ? extract($file_name[1]):null;
                        if (file_exists($this->base_path.'views/'.$file_name[0].'.php')) {
                            require_once($this->base_path.'views/'.$file_name[0].'.php');
                        }else {
                            $file.= $file_name[0];
                            return require_once($this->base_path.'views/error/error.php');
                        }  
                }
            }
            
            //Load Helper
            if ($method == 'helper') {
                $file = "Helper "; $require = array();
                for ($i = 0; $i < count($file_name); $i++) {
                    if (file_exists($this->base_path.'helpers/'.$file_name[$i].'.php')) {
                        $require[] = $this->base_path.'helpers/'.$file_name[$i].'.php';
                    }else {
                        $file.= $file_name[$i].' ';
                    }
                }

                if (count($file_name) == sizeof($require)) {
                    foreach ($require as $key) {
                        require_once($key);
                    }
                }else {
                    return require_once($this->base_path.'views/error/error.php');
                }
            }

            //Load Library
            if ($method == 'library') {
                $file = "Library "; $require = array();
                for ($i = 0; $i < count($file_name); $i++) {
                    if (file_exists($this->base_path.'libraries/'.$file_name[$i].'.php')) {
                        $require[] = $this->base_path.'libraries/'.$file_name[$i].'.php';
                    }else {
                        $file.= $file_name[$i].' ';
                    }
                }
                $i = 0;
                if (count($file_name) == sizeof($require)) {
                    foreach ($require as $key) {
                        require_once($key);
                        $this->{$file_name[$i]} = new $file_name[$i];
                        $i++;
                    }
                }else {
                    return require_once($this->base_path.'views/error/error.php');
                }
            }
            
            //Load Model
            if ($method == 'model') {
                $file = "Model "; $require = array();
                for ($i = 0; $i < count($file_name); $i++) {
                    if (file_exists($this->base_path.'models/'.$file_name[$i].'.php')) {
                        $require[] = $this->base_path.'models/'.$file_name[$i].'.php';
                    }else {
                        $file.= $file_name[$i].' ';
                    }
                }

                if (count($file_name) == sizeof($require)) {
                    $i = 0;
                    require_once($this->base_path.'system/My_Model.php');
                    foreach ($require as $key) {
                        require_once($key);
                        $this->{$file_name[$i]} = new $file_name[$i];
                        $i++;
                    }
                }else {
                    return require_once($this->base_path.'views/error/error.php');
                }
            }

            //Load Database
            if ($method == 'database') {
                require_once($this->base_path.'libraries/QueryBuilder.php');
                $this->db = new QueryBuilder;
            }
        }
    }
?>